name: CI
on: [push]
jobs:
  tailwindcss-update:
    name: Generate Tailwind CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Tailwind CSS
        uses: ZoeyVid/tailwindcss-update@main
        with:
          input: assets/app-tailwind.css
          output: assets/app.css
          params: ""
      - name: Commit & Push
        run: |
          git add --force assets/app.css
          git config user.name "GitHub"
          git config user.email "noreply@github.com"
          git diff-index --quiet HEAD || git commit -m "ci: tailwindcss-update"
          git push
